Whitelists:
  axe:
    - "#mineable/axe"
    - "#leaves"
    - "!BARREL"
    - "!CHEST"
    - "!TRAPPED_CHEST"
    - "!#all_signs"
  pickaxe:
    - "#mineable/pickaxe"
    - "!SPAWNER"
    - "!GILDED_BLACKSTONE"
    - "!DROPPER"
    - "!DISPENSER"
    - "!HOPPER"
    - "!FURNACE"
    - "!BLAST_FURNACE"
    - "!SMOKER"
    - "!#shulker_boxes"
  shovel:
    - "#mineable/shovel"
Placeholders:
  Enabled: true
  StringUtils:
    Enabled: true
    ArgumentSeparator: ","
    AllowCustomSeparator: true
    If:
      ElseIfKeyword: "elseif"
      ElseKeyword: "else"
      ConditionSeparator: "\""
  InvUtils:
    Enabled: true
    FunctionSeparator: "_"
    AllowCustomSeparator: true
    Nbt:
      ArgsSeparator: ","
    Amount:
      ArgsSeparator: ","

Commands:
  AddItemNBT:
    Enabled: true
    Aliases: []

  BlockCycle:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.blockcyclecommand"
    oxidize:
      KeepStairData: true
      KeepSlabData: true
      blocks:
        - CUT_COPPER_STAIRS EXPOSED_CUT_COPPER_STAIRS
        - EXPOSED_CUT_COPPER_STAIRS WEATHERED_CUT_COPPER_STAIRS
        - WEATHERED_CUT_COPPER_STAIRS OXIDIZED_CUT_COPPER_STAIRS
        - OXIDIZED_CUT_COPPER_STAIRS CUT_COPPER_STAIRS
        - WAXED_CUT_COPPER_STAIRS WAXED_EXPOSED_CUT_COPPER_STAIRS
        - WAXED_EXPOSED_CUT_COPPER_STAIRS WAXED_WEATHERED_CUT_COPPER_STAIRS
        - WAXED_WEATHERED_CUT_COPPER_STAIRS WAXED_OXIDIZED_CUT_COPPER_STAIRS
        - WAXED_OXIDIZED_CUT_COPPER_STAIRS WAXED_CUT_COPPER_STAIRS
  BlockGravity:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.blockgravitycommand"

  BoneMealBlock:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.bonemealblockcommand"

  BreakAndReplant:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakandreplantcommand"

  BreakBlockMultiplyDrops:
    Enabled: true
    Aliases: []

  BreakInFacing:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinfacingcommand"

  BreakInFacingLogCoreProtect:
    Enabled: true
    Aliases: []

  BreakInRadius:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinradiuscommand"

  BreakInVein:
    Enabled: true
    Aliases: []
    DefaultCheckClaim: true
    DefaultMaxBlocks: 80
    DefaultTriggerBlockBreakEvent: true

  BreakInXYZ:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.breakinxyzcommand"

  BroadcastMessage:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.broadcastmessagecommand"

  BroadcastConditionMessage:
    Enabled: true
    Aliases: []

  ChanceRandomRun:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.chancerandomruncommand"
    ArgumentSeparator: ",,"
    CommandSeparator: "\\|"

  ChangeVillagerProfession:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.changevillagerprofessioncommand"

  CobwebPrison:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.cobwebprisoncommand"

  CureVillager:
    Enabled: true
    Aliases: []

  CooldownCommand:
    Enabled: true
    Aliases: []
    CooldownMessages:
      Hours: "&cOn Cooldown for %hours%h, %minutes%m, & %seconds%s."
      Minutes: "&cOn Cooldown for %minutes%m & %seconds%s."
      Seconds: "&cOn Cooldown for %seconds%s."
      Milliseconds: "&cOn Cooldown for 0.%milliseconds%s."

  Food:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.foodcommand"

  GetPlayerHead:
    Enabled: true
    Aliases: []

  God:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.godcommand"

  HighlightBlocks:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.highlightblockscommand"
    DefaultParticleOffset: 0.0
    DefaultParticleSpeed: 0.0
    DefaultParticleCount: 1
    DefaultNumberOfIntervals: 40
    DefaultParticleSpawnInterval: 2

  If:
    Enabled: true
    Aliases: []
    ElseIfKeyword: "elseif"
    ElseKeyword: "else"
    CommandSeparator: ",if,"
    ConditionSeparator: "\""

  ItemAttribute:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.itemattributecommand"

  ItemDurability:
    Enabled: true
    Aliases: []

  LaunchFirework:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.launchfireworkcommand"

  LaunchProjectile:
    Enabled: true
    Aliases: []

  LaunchTNT:
    Enabled: true
    Aliases: []

  LoadCrossbow:
    Enabled: true
    Aliases: []
    Permission: "commandutils.command.loadcrossbowcommand"

  Loop:
    Enabled: true
    Aliases: []
    CommandSeparator: ",,"

  MobTarget:
    Enabled: true
    Aliases: []
    #Allow multiple entities in the target selector argument, would randomly choose one
    AllowMultipleTargets: false

  ModifyVelocity:
    Enabled: true

  OverrideEffect:
    Enabled: true
    Aliases: []

  Oxygen:
    Enabled: true
    Aliases: []

  ParsePlaceholder:
    Enabled: true
    Aliases: []

  PreciseEffect:
    Enabled: true
    Aliases: []

  PushEntity:
    Enabled: true
    Aliases: []

  RayTraceParticle:
    Enabled: true
    Aliases: []

  RemoveInRadius:
    Enabled: true
    Aliases: []

  RemoveEntity:
    Enabled: true
    Aliases: []

  RemoveItem:
    Enabled: true
    Aliases: []
    CommandSeparator: ","

  ReplaceInFacing:
    Enabled: true
    Aliases: []

  ReplaceInRadius:
    Enabled: true
    Aliases: []

  ReplaceLore:
    Enabled: true
    Aliases: []

  ReplaceLoreRegex:
    Enabled: true
    Aliases: []

  RunCommandLater:
    Enabled: true
    Aliases: []

  RunCommandWhen:
    Enabled: true
    Aliases: []

  Saturation:
    Enabled: true
    Aliases: []

  ScaleWithCollide:
    Enabled: true
    Aliases: []

  SendBossBar:
    Enabled: true
    Aliases: []

  SendConditionMessage:
    Enabled: true
    Aliases: []

  SendMessage:
    Enabled: true
    Aliases: []
    Use&ForColorCodesByDefault: true
    ParsePlaceholdersByDefault: true
    ColorCodesByDefault: true
    PlayersListArg: false

  SetAI:
    Enabled: true
    Aliases: []

  SetArmorTrim:
    Enabled: true
    Aliases: []

  SetArrowsInBody:
    Enabled: true
    Aliases: []

  SetBeeStingersInBody:
    Enabled: true
    Aliases: []

  SetCompassTracking:
    Enabled: true
    Aliases: []

  SetCursorItem:
    Enabled: true
    Aliases: []

  SetFireTicks:
    Enabled: true
    Aliases: []

  SetFreezeTicks:
    Enabled: true
    Aliases: []

  SetItem:
    Enabled: true
    Aliases: []

  SetItemNBT:
    Enabled: true
    Aliases: []

  SetMobTarget:
    Enabled: true
    Aliases: []

  SetShieldBlockingDelay:
    Enabled: true
    Aliases: []

  SetTNTSource:
    Enabled: true
    Aliases: []
    #Allow selecting multiple tnt's at once to set source, requires restart
    MultipleTNTs: true
    #Allow selecting multiple sources at once, will be a random source if more than one source is provided, requires restart
    MultipleSources: false

  SilentParticle:
    Enabled: true
    Aliases: []

  SpawnBlockBreaker:
    Enabled: true
    Aliases: []

  SpawnGuardianBeam:
    Enabled: true
    Aliases: []

  SpawnNoDamageEvokerFang:
    Enabled: true
    Aliases: []

  SpawnNoDamageFirework:
    Enabled: true
    Aliases: []

  SpawnWitherSkull:
    Enabled: true
    Aliases: []

  TempPlayerVar:
    Enabled: true
    Aliases: []

  TempVar:
    Enabled: true
    Aliases: []

  Waterlog:
    Enabled: true
    Aliases: []

  WeightedRandom:
    Enabled: true
    Aliases: []
    ArgumentSeparator: ",,"
    CommandSeparator: "\\|"

  While:
    Enabled: true
    Aliases: []
    CommandSeparator: "\\|"
    PlaceholderSurrounder: "$"

  ZombifyVillager:
    Enabled: true
    Aliases: []

#Recommended to not change unless you know what your doing
CommandNamespace: "commandutils"